"""Simplified tests for PDF functionality in langextract_docling.

The PDF these tests feed through the wrapper is the generated two-page
`tests/data/report.pdf` (built on demand by the `report_pdf_path` session
fixture), and the text the wrapper must hand to langextract is the
committed `report_pdf.golden.md` snapshot from the same generation run.
Nothing here touches the network: a PDF URL is exercised by serving the
generated bytes through a mocked `requests.get`, so the URL-detection and
download-then-convert branch is still covered end to end.
"""

from pathlib import Path
from unittest import mock

from absl.testing import absltest
from langextract.core import data
import pytest

import langextract_docling as lx

DATA_DIR = Path(__file__).parent / "data"
PDF_PATH = DATA_DIR / "report.pdf"
GOLDEN_MD = DATA_DIR / "report_pdf.golden.md"
PDF_URL = "https://example.invalid/reports/report.pdf"


@pytest.fixture(autouse=True)
def _needs_generated_pdf(report_pdf_path):
  """Every test here converts the generated (gitignored) report.pdf."""


class TestPDFFunctionality(absltest.TestCase):
  """Tests for PDF processing functionality in langextract_docling."""

  def test_pdf_file_processing(self):
    """Test that PDF files are converted to text and sent to langextract."""
    with mock.patch("langextract_docling._original_extract") as mock_extract:
      lx.extract(
          text_or_documents=str(PDF_PATH),
          prompt_description="Test description",
          examples=[],
      )

      mock_extract.assert_called_once()
      actual_text_sent = mock_extract.call_args[1]["text_or_documents"]

      self.assertEqual(GOLDEN_MD.read_text(), actual_text_sent)

  def test_pdf_url_processing(self):
    """Test that PDF URLs are downloaded, converted, and sent to langextract."""
    # fetch_urls defaults to False since langextract 1.6.0, so URL handling
    # must be opted into explicitly.
    fake_response = mock.MagicMock(content=PDF_PATH.read_bytes())
    with (
        mock.patch("langextract_docling._original_extract") as mock_extract,
        mock.patch(
            "langextract_docling.requests.get", return_value=fake_response
        ) as mock_get,
    ):
      lx.extract(
          text_or_documents=PDF_URL,
          prompt_description="Test description",
          examples=[],
          fetch_urls=True,
      )

      mock_get.assert_called_once()
      self.assertEqual(PDF_URL, mock_get.call_args[0][0])

      mock_extract.assert_called_once()
      actual_text_sent = mock_extract.call_args[1]["text_or_documents"]

      # A downloaded PDF must reach langextract as the same markdown a
      # local path would produce.
      self.assertEqual(GOLDEN_MD.read_text(), actual_text_sent)

  def test_pdf_url_not_fetched_without_opt_in(self):
    """Test that a PDF URL stays literal text while fetch_urls is False."""
    with (
        mock.patch("langextract_docling._original_extract") as mock_extract,
        mock.patch("langextract_docling.requests.get") as mock_get,
    ):
      lx.extract(
          text_or_documents=PDF_URL,
          prompt_description="Test description",
          examples=[],
      )

      mock_get.assert_not_called()
      mock_extract.assert_called_once()
      self.assertEqual(PDF_URL, mock_extract.call_args[1]["text_or_documents"])

  def test_non_pdf_file_processing(self):
    """Test that non-PDF files are processed normally (not through PDF path)."""
    # Create a non-PDF file to test
    input_text = "Regular text content"

    # Mock only the original extract function to check the input text
    with mock.patch("langextract_docling._original_extract") as mock_extract:

      # Mock the original extract function to return a known result
      expected_result = data.AnnotatedDocument(
          text="", extractions=[], document_id=None
      )
      mock_extract.return_value = expected_result

      # Call the extract function with regular text
      result = lx.extract(
          text_or_documents=input_text,
          prompt_description="Test description",
          examples=[],
      )

      # Verify that the original extract was called directly with the input text
      mock_extract.assert_called_once()
      call_args = mock_extract.call_args
      self.assertEqual(call_args[1]["text_or_documents"], input_text)

      # Verify the result
      self.assertEqual(result, expected_result)


if __name__ == "__main__":
  absltest.main()
